platform :ios, '5.0'
xcodeproj 'Lemacs.xcodeproj'
pod 'UAGithubEngine'
pod 'UICKeyChainStore'
pod 'HockeySDK'
pod 'SECoreTextView', :git => 'https://github.com/kishikawakatsumi/SECoreTextView.git'
pod 'sundown', '~> 0.1.0'
